version: '3'

services:
  odoo_11:
    build: '.'
    env_file:
      - '.env'
    #command: service nginx start
    #image: 'munrufdocker/odoo11.01'
    hostname: myhost
    ports:
      - '80:80'
    networks:
      mynet:
        ipv4_address: "172.16.238.11"
        ipv6_address: "2001:3984:3989::10"

networks:
  mynet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ip6: "true"
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        #gateway: "172.16.238.1"
        - subnet: "2001:3984:3989::/64"
        #gateway: "2001:3984:3989::1"




